version: '3'
services:
  jekyll:
    build: .
    command: jekyll build -V --watch --incremental --config _config.yml,_config_dev.yml
    image: app_store_srly_io:latest
    volumes:
      - .:/usr/src/app
      - /tmp/asset-cache:/usr/src/app/.asset-cache
    environment:
      - JEKYLL_ENV=development
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./_site:/usr/share/nginx/html
    ports:
      - 8080:80
    depends_on:
      - jekyll
