name: Deploy

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Legacy CI step 1
        run: |
          IMAGE=app_store_srly_io:latest

          docker-compose build

          BUILDARGS="_config.yml"
          echo 'BUILD_ENV=production' >> $GITHUB_ENV

          function run_in_container {
            docker run \
              --rm \
              -v "$(pwd)":/usr/src/app \
              -e JEKYLL_ENV=production \
              "$IMAGE" "$@"
          }

          # This is one insane block of code to deal with
          # various permission errors on CI
          run_in_container rm -rf {.asset-cache,_site}
          run_in_container mkdir -p {.asset-cache/sprockets,_site}
          run_in_container chmod a+rwX -R {.asset-cache,_site}
          run_in_container jekyll build --config "$BUILDARGS"
          run_in_container chmod a+rwX -R {_site,.asset-cache}
          run_in_container rm -rf .asset-cache

          find _site

      - name: Legacy CI step 2
        run: |
          IMAGE=app_store_srly_io:latest

          docker run \
            --rm \
            -v "$(pwd)":/usr/src/app \
            -e JEKYLL_ENV=production \
            "$IMAGE" \
            bundle exec htmlproofer ./_site || true

      - name: Publish
        if: github.event_name != 'pull_request'
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: app-store-production
          directory: _site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          environment: production
